services:
  service-exporter-dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /Users/user/.kube/config.nebula:/home/vscode/.kube/config
      - /Users/user/.netrc:/home/vscode/.netrc
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock